### ISSUE TITLE
Übungen Editieren in scrollable Area einbetten

### ISSUE THREAD

**Issue by Sulkar** [Sulkar/SQLverine-authoring-tool#4]
Damit längere Aufgaben scrollbar sind und die Bedienelemente (Auswahl Aufgaben, Tabs, ...) immer sichtbar bleiben.
![image](https://user-images.githubusercontent.com/10349796/115838351-e3ec8b80-a419-11eb-9a5d-1093dfbf4ede.png)

**Comment by voetzi** [comment]
Viewport implementiert
